updated yaml file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -297,7 +297,36 @@ jobs:
       - name: Terraform Apply
         working-directory: terraform/envs/prod
         run: terraform apply -auto-approve tfplan
+      
+      - name: Health Check (5 min)
+        run: |
+          sleep 300
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://<prod-alb-url>/health)
+          if [ "$STATUS" != "200" ]; then
+            echo "Health check failed!"
+            exit 1
+          fi
+#------------------Rollback--------
+rollback:
+    name: Rollback if Failed
+    runs-on: ubuntu-latest
+    needs: deploy-prod
+    if: failure()
 
+    steps:
+      - name: Configure AWS
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1
+
+      - name: Rollback ECS
+        run: |
+          aws ecs update-service \
+            --cluster infra-pipeline-prod-cluster \
+            --service infra-pipeline-prod-service \
+            --task-definition ${{ needs.deploy-prod.outputs.prev_task }}
 
 
 
